name: Build and Test

on:
  push:
    branches: 
      - "main"
      - "master"
  pull_request:
    branches: 
      - "main"
      - "master"

jobs:
  test-on-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install system dependencies (for tkinter)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests

  build-for-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build .exe using PyInstaller
        run: |
          pyinstaller --onefile annotator.py

      - name: Upload Windows .exe artifact
        uses: actions/upload-artifact@v2
        with:
          name: MiniAnnotator-Windows-Executable
          path: dist/annotator.exe