name: Build and Test

on:
  push:
    branches:
      - "main"
      - "master"
    tags:
      - "v*.*.*"    # Only triggers the 'release' job if the push is a version tag, e.g. v1.0.0
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  test-on-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install system dependencies (for tkinter)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests

  build-for-windows:
    name: Build for Windows
    needs: [test-on-ubuntu]    # This job only runs if 'test-on-ubuntu' finishes successfully
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build .exe using PyInstaller
        run: |
          pyinstaller --onefile MiniAnnotator/annotator.py --name MiniAnnotator

      - name: Upload Windows .exe artifact
        uses: actions/upload-artifact@v3
        with:
          name: MiniAnnotator-Windows-Executable
          path: dist/MiniAnnotator.exe

  release:
    name: Create Release (On Version Tag)
    needs: [ build-for-windows ]  # Only proceeds if build-for-windows passes
    runs-on: ubuntu-latest
    # This condition ensures the release steps only happen for tagged pushes like "v1.0.0"
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Download .exe artifact
        uses: actions/download-artifact@v3
        with:
          name: MiniAnnotator-Windows-Executable
          path: ./dist

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/MiniAnnotator.exe
          asset_name: MiniAnnotator.exe
          asset_content_type: application/octet-stream